Add timer
cmondi18/thinknetica-test-guru pull request #18
Opened 2022-03-24 16:16 UTC by cmondi18

- Add duration of test
- Add js timer

2022-03-24 17:47 UTC, BubuntuClu requested changes

2022-03-24 17:47 UTC, BubuntuClu commented on app/javascript/packs/application.js
> +require("../utilites/timer")
если отключить выполнение js скриптов, то твое ограничение не будет работать и можно будет сколько угодно проходить тест. надо еще на бэке проверять, не вышло ли время

2022-03-25 06:11 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.completed? || @remaining_time <= 0
лучше конечно это все сделать через метод модели, а не через колбэки.
`test_passage.time_expired?` или что-то типа такого. забудешь где-то вызвать колбэк и не будет твоя переменная работать

2022-03-25 07:37 UTC, cmondi18 commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.completed? || @remaining_time <= 0
Не уверен, что это лучшее решение:
1) remaining_time энивей нужно здесь для отображения таймера
2) Получится такой же код, только возвращаемый булеву переменную...

2022-03-25 07:38 UTC, merged