Add auth
cmondi18/thinknetica-test-guru pull request #9
Opened 2022-02-13 11:04 UTC by cmondi18

- Add auth
- Add cookies
- Add login, signup, logout
- Change user model

2022-02-13 18:28 UTC, BubuntuClu requested changes

2022-02-13 18:28 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if session[:return_to].present?
`redirect_to session[:return_to] || root_path`

2022-02-13 18:28 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
может добавить этот колбэк в ApplicationController, чтобы не прописывать в каждом контроллере

2022-02-13 18:28 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
у тебя есть метод `current_user`. так что этот метод тебе вообще не нужен.

2022-02-13 18:28 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
используй регулярку из `URI` модуля.
почему проверка только на создание?(не уверен кстати что такой синтаксис работает) почту могут поменять и при обновлении, тоже стоит проверять что валидно поменяли

2022-02-13 18:28 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
проверку уникальности надо добавить. и не забудь про индекс в БД уникальный создать

2022-02-14 07:04 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params.merge(author: @current_user))
использовать надо метод `current_user`, а не переменную

2022-02-14 07:04 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params.merge(author: @current_user))
о, кстати, пропустил в прошлый раз. тут не надо мержить. у тебя есть ассоциация созданных тестов. используй ее вместо костыля с мержем

2022-02-14 11:49 UTC, cmondi18 commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params.merge(author: @current_user))
Fixed, не подумал о таком решение почему-то изначально :)

2022-02-14 11:49 UTC, merged